### ISSUE TITLE
.NET issue

### ISSUE THREAD

**Issue by XReachlingX** [num0005/Osoyoos-Launcher#27]
When I opened Osoyoos it gave me this message:

![Screenshot 2022-02-06 172612](https://user-images.githubusercontent.com/93212762/152706837-30957a3e-8f2d-42dd-aa0c-c677fbfa9164.png)

It keeps showing that same message every time I attempt to open Osoyoos. even after I have .NET installed and updated.

**Comment by num0005** [comment]
Did you use the link in the readme? 

Download and install the [.NET 5 Desktop Runtime x64](https://dotnet.microsoft.com/download/dotnet/5.0/runtime). It is *very* important that you download the **64-bit** **Desktop** runtime, otherwise the launcher won't start correctly. For convenience you can use the [direct download link]( https://download.visualstudio.microsoft.com/download/pr/2bfb80f2-b8f2-44b0-90c1-d3c8c1c8eac8/409dd3d3367feeeda048f4ff34b32e82/windowsdesktop-runtime-5.0.13-win-x64.exe) but it might point to an older version as this readme is not regularly revised.

**Comment by num0005** [comment]
Closed due to inactivity
